### ISSUE TITLE
Show transactions involved in address and entity relations

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#104] opened 2019-11-06 14:38 UTC
At the moment transaction edges show no_transactions and estimated values. It should be possible to display involved transaction hashes.

(This requires additional tables in the transformation and will therefore go into r.0.5)

**Comment by myrho** [comment] 2020-02-20 14:54
duplicate of #85

**Closed by myrho** 2020-02-20 14:54 UTC
Labels: feature
