### ISSUE TITLE
Same-cluster addresses displayed in several clusters

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-dashboard#400] opened 2023-06-19 08:42 UTC
When I add addresses that are part of the same cluster sequentially, the dashboard creates new clusters. This shouldn't be the case.

Examples for issue reproducibility:

1KeDrQdATuXaZFW4CL9tfe2zpQ5SrmBFWc
1Archive1n2C579dMsAu3iC6tWzuQJz8dN

**Comment by myrho** [comment] 2023-06-19 08:46
Related to #378, possibly duplicate of.

**Closed** 2024-01-11 11:47 UTC
Labels: enhancement
